// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using data.access;

#nullable disable

namespace data.access.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221121063245_Add_Table_ProductExpress")]
    partial class Add_Table_ProductExpress
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("activate_assurance.Models.ProductType", b =>
                {
                    b.Property<int>("productTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productTypeId"), 1L, 1);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnOrder(1);

                    b.Property<int>("isDeleted")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("productTypeId");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("models.ProductExpress", b =>
                {
                    b.Property<int>("productExpressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productExpressId"), 1L, 1);

                    b.Property<bool>("active")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("expirationDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<string>("observations")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnOrder(4);

                    b.Property<double>("price")
                        .HasColumnType("float")
                        .HasColumnOrder(2);

                    b.Property<int>("productTypeId")
                        .HasColumnType("int");

                    b.HasKey("productExpressId");

                    b.HasIndex("productTypeId");

                    b.ToTable("ProductExpresses");
                });

            modelBuilder.Entity("models.ProductExpress", b =>
                {
                    b.HasOne("activate_assurance.Models.ProductType", "productType")
                        .WithMany("productExpresses")
                        .HasForeignKey("productTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productType");
                });

            modelBuilder.Entity("activate_assurance.Models.ProductType", b =>
                {
                    b.Navigation("productExpresses");
                });
#pragma warning restore 612, 618
        }
    }
}
