// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using data.access;

#nullable disable

namespace data.access.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("activate_assurance.Models.ProductType", b =>
                {
                    b.Property<int>("productTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productTypeId"), 1L, 1);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnOrder(1);

                    b.Property<int>("isDeleted")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("productTypeId");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"), 1L, 1);

                    b.Property<bool>("active")
                        .HasColumnType("bit")
                        .HasColumnOrder(2);

                    b.Property<int?>("categoryParentId")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnOrder(1);

                    b.Property<int>("isDeleted")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("categoryId");

                    b.HasIndex("categoryParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("models.erp.module.BarCode", b =>
                {
                    b.Property<int>("barCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("barCodeId"), 1L, 1);

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("isDeleted")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("productExpressId")
                        .HasColumnType("int");

                    b.Property<Guid>("uniqueCode")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("barCodeId");

                    b.HasIndex("productExpressId");

                    b.ToTable("BarCodes");
                });

            modelBuilder.Entity("models.ProductCategory", b =>
                {
                    b.Property<int>("detailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("detailId"), 1L, 1);

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("isDeleted")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("productExpressId")
                        .HasColumnType("int");

                    b.HasKey("detailId");

                    b.HasIndex("categoryId");

                    b.HasIndex("productExpressId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("models.ProductExpress", b =>
                {
                    b.Property<int>("productExpressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productExpressId"), 1L, 1);

                    b.Property<bool>("active")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("expirationDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<int>("isDeleted")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<string>("observations")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnOrder(5);

                    b.Property<double>("price")
                        .HasColumnType("float")
                        .HasColumnOrder(2);

                    b.Property<int>("productTypeId")
                        .HasColumnType("int");

                    b.HasKey("productExpressId");

                    b.HasIndex("productTypeId");

                    b.ToTable("ProductExpresses");
                });

            modelBuilder.Entity("models.SaleExpress", b =>
                {
                    b.Property<int>("saleExpressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("saleExpressId"), 1L, 1);

                    b.Property<string>("clientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<double>("discount")
                        .HasColumnType("float");

                    b.Property<int>("isDeleted")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("productExpressId")
                        .HasColumnType("int");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<double>("total")
                        .HasColumnType("float");

                    b.Property<string>("uniqueCodeProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("saleExpressId");

                    b.HasIndex("productExpressId");

                    b.ToTable("SaleExpresses");
                });

            modelBuilder.Entity("models.erp.module.ProductErp", b =>
                {
                    b.HasBaseType("models.ProductExpress");

                    b.Property<double>("cost")
                        .HasColumnType("float");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.Property<Guid>("uniqueCode")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("ProducstErp", (string)null);
                });

            modelBuilder.Entity("models.Category", b =>
                {
                    b.HasOne("models.Category", "categoryParent")
                        .WithMany("categories")
                        .HasForeignKey("categoryParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("categoryParent");
                });

            modelBuilder.Entity("models.erp.module.BarCode", b =>
                {
                    b.HasOne("models.ProductExpress", "ProductExpress")
                        .WithMany()
                        .HasForeignKey("productExpressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductExpress");
                });

            modelBuilder.Entity("models.ProductCategory", b =>
                {
                    b.HasOne("models.Category", "category")
                        .WithMany("productCategories")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("models.ProductExpress", "productExpress")
                        .WithMany("productCategories")
                        .HasForeignKey("productExpressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("productExpress");
                });

            modelBuilder.Entity("models.ProductExpress", b =>
                {
                    b.HasOne("activate_assurance.Models.ProductType", "productType")
                        .WithMany("productExpresses")
                        .HasForeignKey("productTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productType");
                });

            modelBuilder.Entity("models.SaleExpress", b =>
                {
                    b.HasOne("models.ProductExpress", "productExpress")
                        .WithMany()
                        .HasForeignKey("productExpressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productExpress");
                });

            modelBuilder.Entity("models.erp.module.ProductErp", b =>
                {
                    b.HasOne("models.ProductExpress", null)
                        .WithOne()
                        .HasForeignKey("models.erp.module.ProductErp", "productExpressId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("activate_assurance.Models.ProductType", b =>
                {
                    b.Navigation("productExpresses");
                });

            modelBuilder.Entity("models.Category", b =>
                {
                    b.Navigation("categories");

                    b.Navigation("productCategories");
                });

            modelBuilder.Entity("models.ProductExpress", b =>
                {
                    b.Navigation("productCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
